# Create a new release when the package.json version tag changes

name: Create Release On Package Version

on:
  push:
    branches:
      - "master"

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/version-check@v2.0.1
        id: check
        with:
          diff-search: true
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
      type: ${{ steps.check.outputs.type }}
  typescript-build:
    needs: version-check
    if: needs.version-check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install
      - run: npm run build
  github-release:
    needs: [version-check, typescript-build]
    if: needs.version-check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.version-check.outputs.version }}
          name: 'Version Update: ${{ needs.version-check.outputs.version }} (${{ needs.version-check.outputs.type }})'
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: [version-check, typescript-build]
    if: needs.version-check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
